word_pairs = [
    [["capital"], ["ensisijainen", "pääasiallinen"]],
    [["expenditure"], ["rahankäyttö"]],
    [["targible"], ["aineellinen"]],
    [["provisioned"], ["varustettu"]],
    [["decentralized"], ["hajautettu"]],
    [["compliance"], ["ohjeidenmukaisuus"]],
    [["upon"], ["tiettynä aikana"]],
    [["establish"], ["vakiinnuttaa", "perustaa", "tehdä"]],
    [["domain"], ["verkkotunnus", "määrittelyjoukko", "kenttä", "toimialue"]],
    [["mine"], ["louhia"]],
    [["insight"], ["oivaltaminen"]],
    [["reinforce", "fortify"], ["vahvistaa"]],
    [["poise"], ["tasapaino", "olemus", "valmius", "kyky tehdä jotain"]],
    [["further"], ["edistää"]],
    [["bottom line"], ["lopputulos"]],
    [["reduction"], ["alennus", "vähennys"]],
    [["perishable"], ["pilaantuva"]],
    [["mundane"], ["maallinen", "jokapäiväinen"]],
    [["ubiquity"], ["kaikkialla läsnäolo"]],
    [["dispenser"], ["jakelulaite"]],
    [["gadget"], ["laite", "vehje"]],
    [["imply"], ["merkitä", "sisältää", "seurata"]],
    [["assumption"], ["olettamus"]],
    [["denote"], ["merkitä"]],
    [["consequently"], ["niinpä", "siksi", "niin"]],
    [["inverse"], ["käänteisarvo"]],
    [["advance"], ["siirtää eteenpäin", "edetä"]],
    [["elaborate"], ["täsmentää"]],
    [["precede"], ["edeltää"]],
    [["substitute"], ["korvata"]],
    [["multidisciplinary"], ["monitieteellinen"]],
    [["devoted"], ["innokas"]],
    [["compulsory", "mandatory"], ["pakollinen"]],
    [["embark"], ["aloittaa"]],
    [["substantial"], ["olennainen"]],
    [["enhance"], ["parantaa"]],
    [["prospect"], ["mahdollisuus"]],
    [["pursue"], ["tavoitella"]],
    [["comprehensive"], ["laaja"]],
    [["manufacturer"], ["valmistaja"]],
    [["prestigious"], ["arvovaltainen", "maineikas"]],
    [["scholarship"], ["apuraha"]],
    [["tuition fee"], ["lukukausimaksu"]],
    [["monetary"], ["rahallinen"]],
    [["inanimate"], ["eloton", "liikkumaton"]],
    [["surveillance"], ["valvonta"]],
    [["a tad"], ["hiukan"]],
    [["sentience"], ["tietoisuus"]],
    [["havoc"], ["vahinko"]],
    [["divert"], ["kääntää pois", "harhauttaa"]],
    [["unsettling"], ["huolestuttava"]],
    [["downright"], ["suoranainen"]],
    [["paramount"], ["tärkein"]],
    [["shore up"], ["tukea"]],
    [["gadget"], ["laite", "vimpain"]],
    [["occupant"], ["asukas"]],
    [["unveil"], ["paljastaa", "julkistaa"]],
    [["ubiquitous"], ["kaikkialla läsnäoleva"]],
    [["contribute to"], ["olla osallisena", "edistää"]],
    [["hub"], ["keskitin"]],
    [["vicinity"], ["lähiympäristö", "läheisyys"]],
    [["conjunction"], ["yhdistäminen", "yhteys"]],
    [["outlet"], ["pistorasia", "ulostulo"]],
    [["firmware"], ["laiteohjelma", "sulautettu ohjelma"]],
    [["offload"], ["sysätä"]],
    [["unsolicited"], ["pyytämätön"]],
    [["itinerary"], ["reitti"]],
    [["to tell votes"], ["laskea ääniä"]],
    [["teller"], ["ääntenlaskija"]],
    [["alleviate"], ["helpottaa", "lievittää"]],
    [["rectify"], ["oikaista", "korjata"]],
    [["feasibility study"], ["kannattavuustutkimus", "soveltuvuustutkimus"]],
    [["appliance"], ["kodinkone"]],
    [["toll"], ["tiemaksu", "maksu", "tulli"]],
    [["tag"], ["merkki", "lappu", "tunniste"]],
    [["garment"], ["vaatekappale"]],
    [["defect"], ["virhe"]],
    [["soil"], ["maaperä", "lika", "multa"]],
    [["crop"], ["vilja", "sato"]],
    [["irrigation"], ["kastelu"]],
    [["livestock"], ["karja"]],
    [["award"], ["myöntää", "tuomita"]],
    [["disclosure"], ["paljastaminen"]],
    [["connectivity"], ["liitettävyys"]],
    [["subscriber"], ["liittymän omistaja"]],
    [["access control"], ["käyttöoikeuksien hallinta"]],
    [
        ["Advanced Persistent Threat"],
        ["kohdistettu haittaohjelmahyökkäys", "edistynyt pitkäkestoinen uhka"],
    ],
    [["contingency plan"], ["varautumissuunnitelma"]],
    [["hacking"], ["tietomurto"]],
    [["intrusion"], ["tunkeutuminen"]],
    [["authenticity"], ["alkuperäisyys"]],
    [["hoax"], ["huijaus", "huijausvaroitus"]],
    [["availability"], ["käytettävyys", "saatavuus"]],
    [["authorization"], ["käyttövaltuus"]],
    [["confidentiality"], ["luottamuksellisuus"]],
    [["unauthorized user"], ["luvaton käyttäjä"]],
    [["mobile certificate"], ["mobiilivarmenne"]],
    [["data integrity"], ["tiedon eheys"]],
    [["data protection"], ["tietosuoja"]],
    [["information security incident"], ["tietoturvahäiriö"]],
    [["cyber crime"], ["tietoverkkorikos"]],
    [["identification"], ["tunnistus", "tunnistaminen"]],
    [["security surveillance"], ["turvallisuusvalvonta"]],
    [["forgery"], ["väärennös"]],
    [["virus alert"], ["virusvaroitus"]],
    [["digital forensics"], ["tietoturvaloukkauksen tutkinta"]],
    [["digital identity"], ["sähköinen henkilöllisyys"]],
    [["telemetry"], ["kaukomittaus"]],
    [["security breach"], ["tietoturvaloukkaus"]],
    [["forwarding of traffic"], ["tietoliikenteen välitys"]],
    [["communication protocol"], ["yhteyskäytäntö"]],
    [["ransomware"], ["kiristysohjelma"]],
    [["phising"], ["verkkourkinta"]],
    [["authentication"], ["todennus"]],
    [["rerouting email"], ["sähköpostin uudelleenohjaus"]],
    [["free-choice electives"], ["vapaasti valittavat opinnot"]],
    [["bachelor's thesis"], ["opinnäytetyö"]],
    [["practical training", "internship"], ["harjoittelu"]],
    [["to take a degree"], ["suorittaa tutkinto"]],
]


word_pairs2 = [
    [["bit"], ["binaariluku"]],
    [["processing"], ["käsittely"]],
    [["interface"], ["käyttöliittymä"]],
    [["crystal"], ["kide"]],
    [["markup"], ["merkkaus"]],
    [["positioning"], ["paikannus"]],
    [["circuit board"], ["piirilevy"]],
    [["object-oriented"], ["olioperustainen"]],
    [["printed"], ["painettu"]],
    [["serial"], ["sarja-"]],
    [["transfer"], ["siirto"]],
    [["integrated"], ["sisäänrakennettu"]],
    [["frequency"], ["taajuus"]],
    [["communications"], ["tietoliikenne"]],
    [["bus"], ["väylä"]],
    [["network"], ["verkko"]],
    [["aided"], ["avusteinen"]],
    [["integrated circuit"], ["mikropiiri"]],
    [["conductivity"], ["johtokyky", "johtavuus"]],
    [["furnance"], ["sulatusuuni"]],
    [["hermetically"], ["ilmatiiviisti"]],
    [["crate"], ["kori", "laatikko"]],
    [["cardboard"], ["kartonki", "pahvi"]],
    [["dopant"], ["seostusaine"]],
    [["diameter"], ["halkaisija", "läpimitta"]],
    [["lapping"], ["hiominen", "hierto"]],
    [["grinding"], ["jauhaminen", "murskaaminen", "hierto"]],
    [["wavelength"], ["aallonpituus"]],
    [["debug"], ["poistaa virheet"]],
    [["bandwidth"], ["kaistanleveys"]],
    [["fixed"], ["määrätty"]],
    [["allocation"], ["kohdennus", "kohdentaminen"]],
    [["capability"], ["kyky"]],
    [["compiler"], ["kääntäjä"]],
    [["device"], ["laite"]],
    [["hardware"], ["laitteisto"]],
    [["wireless"], ["langaton"]],
    [["forward"], ["lähettää eteenpäin"]],
    [["peripheral"], ["oheislaite"]],
    [["software"], ["ohjelmisto"]],
    [["bug"], ["ohjelmointivirhe"]],
    [["access"], ["pääsy", "oikeus käyttää"]],
    [["characteristic"], ["ominaisuus"]],
    [["server"], ["palvelin"]],
    [["speech recognition"], ["puheentunnistus"]],
    [["router"], ["reititin"]],
    [["achieve"], ["saavuttaa"]],
    [["encryption"], ["salaus"]],
    [["node"], ["solmukohta"]],
    [["application"], ["sovellus"]],
    [["data security"], ["tietoturvallisuus"]],
    [["storage space"], ["tallennustila"]],
    [["cache"], ["välimuisti"]],
    [["backbone"], ["runkoverkko"]],
    [["malware"], ["haittaohjelma"]],
    [["information security threat"], ["tietoturvauhka"]],
    [["security breach"], ["tietoturvaloukkaus"]],
    [["identification"], ["tunnistus", "tunnistaminen"]],
    [["data transmission"], ["tiedonsiirto"]],
    [["thwart"], ["estää", "pysäyttää"]],
    [["pattern"], ["kaava", "malli", "kuvio"]],
    [["deviation"], ["poikkeama", "poikkeavuus"]],
    [["administrator"], ["ylläpitäjä"]],
    [["objection"], ["vastustus"]],
    [["dissention", "dissonance", "animosity", "dissent"], ["erimielisyys"]],
    [["to address"], ["käsitellä"]],
    [["bid", "offer", "quation", "tender"], ["tarjous"]],
    [["bargaining"], ["kaupankäynti"]],
    [["agreeing on procedures"], ["menettelytavoista sopiminen"]],
    [["bidding"], ["tarjouksen tekeminen", "kilpailuttaminen"]],
    [["opponent"], ["vastapuoli"]],
    [["aim"], ["tavoite", "aikomus", "päämäärä"]],
    [["concession"], ["myönnytys"]],
    [["congestion"], ["ruuhka"]],
    [["downtime"], ["häiriöaika"]],
    [["impend"], ["uhata"]],
    [["opinnäytetyön työstäminen"], ["working on thesis study"]],
    [["rakennustekniikka"], ["construction engineering"]],
    [["opetussuunnitelma"], ["curriculum"]],
]


word_pairs3 = [
    [["data transmission"], ["tiedonsiirto"]],
    [["thwart"], ["estää", "pysäyttää"]],
    [["pattern"], ["kaava", "malli", "kuvio"]],
    [["deviation"], ["poikkeama", "poikkeavuus"]],
    [["administrator"], ["ylläpitäjä"]],
    [["objection"], ["vastustus"]],
    [["dissention", "dissonance", "animosity", "dissent"], ["erimielisyys"]],
    [["to address"], ["käsitellä"]],
    [["bid", "offer", "quatation", "tender"], ["tarjous"]],
    [["bargaining"], ["kaupankäynti"]],
    [["agreeing on procedures"], ["menettelytavoista sopiminen"]],
    [["bidding"], ["tarjouksen tekeminen", "kilpailuttaminen"]],
    [["opponent"], ["vastapuoli"]],
    [["aim"], ["tavoite", "aikomus", "päämäärä"]],
    [["concession"], ["myönnytys"]],
    [["congestion"], ["ruuhka"]],
    [["downtime"], ["häiriöaika"]],
    [["impend"], ["uhata"]],
    [["working on thesis study"], ["opinnäytetyön työstäminen"]],
    [["construction engineering"], ["rakennustekniikka"]],
    [["curriculum"], ["opetussuunnitelma"]],
]
